---
spring:
  profiles: default
  application:
    name: QuizApplication
  data:
    mongodb:
      uri: mongodb+srv://admin:admin123@cluster0.2cccy8p.mongodb.net/?retryWrites=true&w=majority
      dbName: quizmaster
server:
  port: 8080

logging:
  level:
    root: INFO
